//! The reference file (DESIGN §1): about 100 MB, a header and 1M rows of 12
//! columns, UTF-8, with quoted fields that contain some newlines.
//!
//! It is generated, never committed. The output is a pure function of the
//! row count and the seed, so every machine writes the same bytes;
//! `crates/leal-bench/reference.sha256` pins the SHA-256 of the default file
//! and `just reference-file` checks it.
//!
//! The file is regular: LF line endings, no BOM, every row has 12 fields,
//! and fields are quoted exactly when they contain a comma, a quote or a
//! newline (the way most CSV writers quote). So it measures the common path.
//! Messy input is the corpus's job (`tests/corpus/`).
//!
//! | Column | Contents |
//! |---|---|
//! | `id` | 1, 2, 3, … |
//! | `order_date` | `2015-01-01` to `2025-12-28` |
//! | `customer` | `"Surname, Given"`, always quoted; many names are non-ASCII |
//! | `city` | Includes `São Paulo`, `東京`, `Αθήνα` and `"Washington, D.C."` |
//! | `country` | ISO 3166 code matching the city |
//! | `sku` | `SKU-00000` to `SKU-99999` |
//! | `quantity` | Mostly 1–9 |
//! | `unit_price` | `0.99` to `500.98` |
//! | `currency` | ISO 4217 code matching the country |
//! | `discount` | Usually empty, otherwise `0.05` to `0.25` |
//! | `status` | `shipped`, `delivered`, `pending`, … |
//! | `notes` | Usually empty; free text, some with commas, escaped quotes (`""`) or newlines |

use std::fs::{self, File};
use std::io::{self, BufWriter, Write};
use std::path::{Path, PathBuf};

/// Data rows in the reference file (it also has a header row).
pub const ROWS: u64 = 1_000_000;

/// The seed for the reference file.
pub const SEED: u64 = 0x4c45_414c; // "LEAL"

/// The generator's version. Bump it whenever the output changes, so that a
/// file generated by an older version (cached under the old name) is never
/// mistaken for the current one. `tests/reference.rs` pins the output.
pub const VERSION: u32 = 1;

/// Fields per row.
pub const COLUMNS: usize = 12;

/// The header row, without its line ending.
pub const HEADER: &str =
    "id,order_date,customer,city,country,sku,quantity,unit_price,currency,discount,status,notes";

/// The reference file's name, which includes [`VERSION`].
#[must_use]
pub fn file_name() -> String {
    format!("reference-v{VERSION}.csv")
}

/// Where generated files go: `$LEAL_BENCH_DATA` if set, otherwise
/// `target/bench-data/` in the workspace, which git ignores.
#[must_use]
pub fn data_dir() -> PathBuf {
    if let Some(dir) = std::env::var_os("LEAL_BENCH_DATA") {
        return PathBuf::from(dir);
    }
    // This crate is `<workspace>/crates/leal-bench`.
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace = manifest.ancestors().nth(2).unwrap_or(manifest);
    workspace.join("target").join("bench-data")
}

/// The reference file's path, in [`data_dir`].
#[must_use]
pub fn path() -> PathBuf {
    data_dir().join(file_name())
}

/// Returns the reference file's path, generating the file first if it isn't
/// there. Benchmarks call this, so they work from a clean checkout.
///
/// # Errors
///
/// Any error creating or writing the file.
pub fn ensure() -> io::Result<PathBuf> {
    let path = path();
    if !path.is_file() {
        generate(&path, ROWS, SEED)?;
    }
    Ok(path)
}

/// Writes a reference file with `rows` data rows to `path`, creating its
/// directory, and returns its size in bytes. The file appears complete or
/// not at all: it is written under a temporary name and then renamed.
///
/// # Errors
///
/// Any error creating, writing or renaming the file.
pub fn generate(path: &Path, rows: u64, seed: u64) -> io::Result<u64> {
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir)?;
    }
    let name = path.file_name().unwrap_or_default().to_string_lossy();
    let partial = path.with_file_name(format!(".{name}.{}.partial", std::process::id()));
    let written = File::create(&partial).and_then(|file| {
        let mut out = BufWriter::with_capacity(1 << 20, file);
        let written = write(&mut out, rows, seed)?;
        out.flush()?;
        Ok(written)
    });
    match written {
        Ok(written) => {
            fs::rename(&partial, path)?;
            Ok(written)
        }
        Err(error) => {
            // Best effort: the write already failed, and that error matters more.
            let _ = fs::remove_file(&partial);
            Err(error)
        }
    }
}

/// Writes the header and `rows` data rows to `out`, and returns the number
/// of bytes written. The same `rows` and `seed` always give the same bytes,
/// and fewer rows give a prefix of the same file.
///
/// # Errors
///
/// Any error from `out`.
pub fn write<W: Write + ?Sized>(out: &mut W, rows: u64, seed: u64) -> io::Result<u64> {
    let mut rng = Rng(seed);
    let mut line = Vec::with_capacity(512);
    let mut text = String::with_capacity(256);

    line.extend_from_slice(HEADER.as_bytes());
    line.push(b'\n');
    out.write_all(&line)?;
    let mut written = line.len() as u64;

    for id in 1..=rows {
        line.clear();
        write_row(&mut line, &mut text, &mut rng, id)?;
        out.write_all(&line)?;
        written += line.len() as u64;
    }
    Ok(written)
}

/// Appends one data row, with its line ending, to `line`. The order of the
/// random draws is part of the output: changing it changes the file.
fn write_row(line: &mut Vec<u8>, text: &mut String, rng: &mut Rng, id: u64) -> io::Result<()> {
    // id, order_date
    write!(
        line,
        "{id},{}-{:02}-{:02},",
        2015 + rng.below(11),
        1 + rng.below(12),
        1 + rng.below(28)
    )?;

    // customer: "Surname, Given"
    text.clear();
    text.push_str(rng.pick(SURNAMES));
    text.push_str(", ");
    text.push_str(rng.pick(GIVEN_NAMES));
    push_field(line, text);
    line.push(b',');

    // city, country, sku, quantity, unit_price, currency
    let &(city, country, currency) = rng.pick(CITIES);
    push_field(line, city);
    let quantity = if rng.chance(85) {
        1 + rng.below(9)
    } else {
        10 + rng.below(240)
    };
    let cents = 99 + rng.below(50_000);
    write!(
        line,
        ",{country},SKU-{:05},{quantity},{}.{:02},{currency},",
        rng.below(100_000),
        cents / 100,
        cents % 100
    )?;

    // discount, status
    if rng.chance(30) {
        line.extend_from_slice(rng.pick(DISCOUNTS).as_bytes());
    }
    line.push(b',');
    line.extend_from_slice(status(rng.below(100)).as_bytes());
    line.push(b',');

    // notes
    write_notes(text, rng);
    push_field(line, text);
    line.push(b'\n');
    Ok(())
}

/// Fills `text` with the notes field: usually empty, otherwise a sentence or
/// two, some with a comma, a quoted phrase or a newline.
fn write_notes(text: &mut String, rng: &mut Rng) {
    text.clear();
    let kind = rng.below(1000);
    match kind {
        // Empty.
        0..530 => {}
        // Several lines: the "quoted fields containing some newlines".
        530..560 => {
            let lines = 2 + rng.below(2);
            for n in 0..lines {
                if n > 0 {
                    text.push('\n');
                }
                push_sentence(text, rng, 3, 5);
            }
        }
        // A quoted phrase, written with escaped quotes ("").
        560..580 => {
            text.push_str("customer wrote \"");
            push_sentence(text, rng, 2, 4);
            text.push('"');
        }
        // A sentence, sometimes with a comma.
        _ => {
            push_sentence(text, rng, 2, 7);
            if rng.chance(20) {
                text.push_str(", ");
                push_sentence(text, rng, 1, 3);
            }
        }
    }
}

/// Appends `min` to `min + spread - 1` words.
fn push_sentence(text: &mut String, rng: &mut Rng, min: u64, spread: u64) {
    let words = min + rng.below(spread);
    for n in 0..words {
        if n > 0 {
            text.push(' ');
        }
        text.push_str(rng.pick(WORDS));
    }
}

/// Appends `value` as a CSV field, quoted only if it contains a comma, a
/// quote or a newline, with any quotes doubled.
fn push_field(line: &mut Vec<u8>, value: &str) {
    if value.contains([',', '"', '\n']) {
        line.push(b'"');
        for &byte in value.as_bytes() {
            if byte == b'"' {
                line.push(b'"');
            }
            line.push(byte);
        }
        line.push(b'"');
    } else {
        line.extend_from_slice(value.as_bytes());
    }
}

/// The status for a draw in `0..100`.
fn status(draw: u64) -> &'static str {
    match draw {
        0..55 => "shipped",
        55..75 => "delivered",
        75..87 => "pending",
        87..93 => "cancelled",
        93..98 => "returned",
        _ => "on hold",
    }
}

/// SplitMix64: a small, fast generator whose output is fixed by its
/// definition, so it can never change under us the way a library's
/// generator might between versions. Not for cryptography.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    /// A number in `0..n`. (The modulo is very slightly biased, which
    /// doesn't matter for test data.)
    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }

    /// True `percent`% of the time.
    fn chance(&mut self, percent: u64) -> bool {
        self.below(100) < percent
    }

    fn pick<T>(&mut self, items: &'static [T]) -> &'static T {
        let len = u64::try_from(items.len()).unwrap_or(u64::MAX);
        let index = usize::try_from(self.below(len)).unwrap_or(0);
        &items[index]
    }
}

const GIVEN_NAMES: &[&str] = &[
    "James",
    "Mary",
    "José",
    "Zoë",
    "Aiko",
    "Øyvind",
    "Chloé",
    "Mohammed",
    "Wei",
    "Priya",
    "Siobhán",
    "Lars",
    "Fatima",
    "Mateo",
    "Ingrid",
    "Kenji",
    "Amélie",
    "Olu",
    "Björn",
    "Ana",
    "Dmitri",
    "Leila",
    "Tomás",
    "Hana",
    "Noah",
    "Emma",
    "Liam",
    "Sofia",
    "Arjun",
    "Mei",
    "Katherine \"Kit\"",
    "Jürgen",
];

const SURNAMES: &[&str] = &[
    "Smith",
    "Müller",
    "García",
    "Nguyễn",
    "O'Brien",
    "Kowalski",
    "Rossi",
    "田中",
    "Dubois",
    "Silva",
    "Novák",
    "Johansson",
    "Kim",
    "Patel",
    "Ivanova",
    "Okafor",
    "van der Berg",
    "Søreide",
    "Łukasiewicz",
    "Brown",
    "Wilson",
    "Martin",
    "Lee",
    "Andersson",
    "Fernández",
    "Hoffmann",
    "Yılmaz",
    "Murphy",
    "Costa",
    "Schmidt",
    "Haddad",
    "Tanaka",
];

/// (city, country, currency)
const CITIES: &[(&str, &str, &str)] = &[
    ("London", "GB", "GBP"),
    ("Manchester", "GB", "GBP"),
    ("Paris", "FR", "EUR"),
    ("Montréal", "CA", "CAD"),
    ("Toronto", "CA", "CAD"),
    ("Zürich", "CH", "CHF"),
    ("São Paulo", "BR", "BRL"),
    ("Kraków", "PL", "PLN"),
    ("東京", "JP", "JPY"),
    ("大阪", "JP", "JPY"),
    ("New York", "US", "USD"),
    ("Washington, D.C.", "US", "USD"),
    ("Austin", "US", "USD"),
    ("Berlin", "DE", "EUR"),
    ("München", "DE", "EUR"),
    ("Reykjavík", "IS", "ISK"),
    ("Αθήνα", "GR", "EUR"),
    ("Dublin", "IE", "EUR"),
    ("Lisboa", "PT", "EUR"),
    ("서울", "KR", "KRW"),
    ("Mumbai", "IN", "INR"),
    ("Lagos", "NG", "NGN"),
    ("Sydney", "AU", "AUD"),
    ("Ciudad de México", "MX", "MXN"),
    ("Göteborg", "SE", "SEK"),
    ("Kyiv", "UA", "UAH"),
    ("İstanbul", "TR", "TRY"),
    ("Cairo", "EG", "EGP"),
    ("Amsterdam", "NL", "EUR"),
    ("Oslo", "NO", "NOK"),
    ("Wellington", "NZ", "NZD"),
    ("Singapore", "SG", "SGD"),
];

const DISCOUNTS: &[&str] = &["0.05", "0.10", "0.15", "0.20", "0.25"];

const WORDS: &[&str] = &[
    "please",
    "deliver",
    "after",
    "before",
    "noon",
    "weekend",
    "call",
    "customer",
    "on",
    "arrival",
    "gift",
    "wrap",
    "fragile",
    "handle",
    "with",
    "care",
    "leave",
    "at",
    "door",
    "reception",
    "back",
    "office",
    "invoice",
    "attached",
    "reorder",
    "next",
    "month",
    "priority",
    "shipping",
    "requested",
    "damaged",
    "box",
    "replacement",
    "sent",
    "refund",
    "issued",
    "address",
    "updated",
    "contact",
    "by",
    "email",
    "the",
    "to",
    "for",
    "warehouse",
    "café",
    "Straße",
    "délai",
];
