"""Aggregate grid-spike run JSON files into Markdown (results.md).
Usage: python3 aggregate.py runs/ > results.md"""
import glob
import json
import os
import statistics
import subprocess
import sys
from collections import defaultdict

d = sys.argv[1] if len(sys.argv) > 1 else "runs"
runs = [json.load(open(p)) | {"_file": os.path.basename(p)} for p in sorted(glob.glob(os.path.join(d, "run-*.json")))]
if not runs:
    sys.exit("no runs")

ORDER = {"A": 0, "A-lite": 1, "B": 2}


def key(r):
    return (r["speed"], ORDER.get(r["variant"], 9), r["cols"])


def profile(speed):
    return "fast fling (60,000 pt/s)" if speed >= 60000 else f"moderate ({speed:,.0f} pt/s)"


def med(xs):
    xs = [x for x in xs if x is not None]
    return statistics.median(xs) if xs else float("nan")


groups = defaultdict(list)
for r in runs:
    groups[(r["speed"], r["variant"], r["cols"])].append(r)

r0 = runs[0]
try:
    disp = subprocess.run(["system_profiler", "SPDisplaysDataType"], capture_output=True, text=True).stdout
    disp = " ".join(l.strip() for l in disp.splitlines() if "Resolution" in l or "Display Type" in l)
except Exception:
    disp = "?"

print("# Grid spike raw results (PLAN 0.4)\n")
print("Generated by `./bench.sh run` and `aggregate.py`. See `docs/tasks/0.4.md` for method and caveats.\n")
print("## Environment\n")
print(f"- Mac: `{r0['hwModel']}` ({r0['cpu']}), {r0['osVersion']}")
print(f"- Window on: {r0['screenName']}, {r0['screenMaxFPS']} Hz max, backing scale {r0['backingScale']:.0f}×; "
      f"measured display-link frame duration {r0['refreshMsMedian']:.2f} ms")
print(f"- Displays (`system_profiler SPDisplaysDataType`): {disp}")
print(f"- Window 1200 × 780 pt, 1,000,000 rows, per-cell styling on, one in-cell editor open")
print("- **The screen was locked during all runs** (owner away): the app lays out, draws and commits every "
      "frame, but WindowServer does not composite the window. Numbers are main-thread cost; compositor/GPU "
      "hitches are not captured.\n")
print("Metric definitions: *frame* = interval between display-link callbacks (vsync-quantised, so 8.33 ms = on "
      "time at 120 Hz); *>8.3* = frames that missed at least one refresh (interval > 12.5 ms); *>16.7* = missed "
      "two or more (> 20.8 ms); *busy* = main-thread time per frame (wall time minus run-loop sleep); "
      "*footprint* = `phys_footprint` (what `footprint(1)` reports, including graphics surfaces); *heap* = "
      "malloc bytes in use. Scroll stats pool the vertical, horizontal and wide-vertical phases; the jump to "
      "the end is reported separately.\n")

for speed in sorted({r["speed"] for r in runs}, reverse=True):
    print(f"## Medians: {profile(speed)}\n")
    print("| Variant | Cols | Runs | Frame p50 | p95 | p99 | >8.3 ms | >16.7 ms | Frames | Late % | Busy p50 | Busy p99 | Jump to end | Edit commit+draw |")
    print("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for (sp, v, c), rs in sorted(groups.items(), key=lambda kv: (ORDER.get(kv[0][1], 9), kv[0][2])):
        if sp != speed:
            continue
        s = lambda f: med([f(r) for r in rs])
        late = s(lambda r: 100 * r["scroll"]["over8"] / max(1, r["scroll"]["frames"]))
        print(f"| {v} | {c} | {len(rs)} | {s(lambda r: r['scroll']['p50']):.1f} | {s(lambda r: r['scroll']['p95']):.1f} | "
              f"{s(lambda r: r['scroll']['p99']):.1f} | {s(lambda r: r['scroll']['over8']):.0f} | {s(lambda r: r['scroll']['over16']):.0f} | "
              f"{s(lambda r: r['scroll']['frames']):.0f} | {late:.1f}% | {s(lambda r: r['busy']['p50']):.1f} | {s(lambda r: r['busy']['p99']):.1f} | "
              f"{s(lambda r: r['jumpEndMs']):.1f} | {s(lambda r: r['editCommitAndDrawMs']):.1f} |")
    print()
    print("| Variant | Cols | Launch → first rows (ms) | of which column auto-size | Footprint after load (MB) | Peak | After scroll | Heap after load (MB) | Heap peak | Heap after scroll | Layers after load | Views created / cells drawn |")
    print("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for (sp, v, c), rs in sorted(groups.items(), key=lambda kv: (ORDER.get(kv[0][1], 9), kv[0][2])):
        if sp != speed:
            continue
        s = lambda f: med([f(r) for r in rs])
        cnt = rs[0]["counters"]
        work = f"{cnt.get('cellViewsCreated', 0):,} views" if "cellViewsCreated" in cnt else f"{cnt.get('cellsDrawn', 0):,} cells"
        print(f"| {v} | {c} | {s(lambda r: r['launchToFirstFrameMs']):.0f} | {s(lambda r: r['autosizeMs']):.0f} | "
              f"{s(lambda r: r['footprintAfterLoadMB']):.0f} | {s(lambda r: r['footprintPeakMB']):.0f} | {s(lambda r: r['footprintAfterScrollMB']):.0f} | "
              f"{s(lambda r: r.get('heapAfterLoadMB')):.1f} | {s(lambda r: r.get('heapPeakMB')):.1f} | {s(lambda r: r.get('heapAfterScrollMB')):.1f} | "
              f"{s(lambda r: r.get('layersAfterLoad')):.0f} | {work} |")
    print()
    print("Per phase (median of runs; frame p50 / p99 / late frames):\n")
    print("| Variant | Cols | Vertical | Horizontal | Vertical, scrolled right |")
    print("|---|---:|---|---|---|")
    for (sp, v, c), rs in sorted(groups.items(), key=lambda kv: (ORDER.get(kv[0][1], 9), kv[0][2])):
        if sp != speed:
            continue
        cells = []
        for ph in ["vertical", "horizontal", "verticalWide"]:
            p = [r["phases"].get(ph) for r in rs if r["phases"].get(ph)]
            if not p:
                cells.append("–")
                continue
            cells.append(f"{med([x['p50'] for x in p]):.1f} / {med([x['p99'] for x in p]):.1f} / "
                         f"{med([x['over8'] for x in p]):.0f} of {med([x['frames'] for x in p]):.0f}")
        print(f"| {v} | {c} | " + " | ".join(cells) + " |")
    print()

print("## Every run\n")
print("| File | Frame p50 | p99 | >8.3 | >16.7 | Frames | Busy p50 | Jump | Launch→rows | FP load | FP peak | FP after | Heap after | Edit ok |")
print("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|")
for r in sorted(runs, key=lambda r: (key(r), r["_file"])):
    s = r["scroll"]
    print(f"| {r['_file']} | {s['p50']:.1f} | {s['p99']:.1f} | {s['over8']} | {s['over16']} | {s['frames']} | "
          f"{r['busy']['p50']:.1f} | {r['jumpEndMs']:.1f} | {r['launchToFirstFrameMs']:.0f} | {r['footprintAfterLoadMB']:.0f} | "
          f"{r['footprintPeakMB']:.0f} | {r['footprintAfterScrollMB']:.0f} | {r.get('heapAfterScrollMB', 0):.1f} | {r['editVerified']} |")
